name: Build SmmMem Drivers

on:
  workflow_dispatch: # Кнопка ручного запуску в інтерфейсі

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Add MSBuild and DevCmd to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Run Release Build Script
      shell: cmd
      run: |
        call src\build.cmd

    - name: Run Debug Build Script
      shell: cmd
      run: |
        call src_dbg01\build.cmd

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SmmMem-Binaries
        path: Work/build/*
